# Site settings
title: "Ilios"
email: support@iliosproject.org
description: >
    Curriculum Management for the Health Professions
baseurl: ""
url: "https://ilios.github.io"
github_username:  ilios
# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, LICENSE]
gems:
  - jekyll-mentions
